<?xml version="1.0" encoding="utf-8"?><Database Name="Cars" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Cars.mdf;Integrated Security=True" SettingsObjectName="CarRental.Properties.Settings" SettingsPropertyName="CarsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Equipments" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Equipment_Car" Member="Equipment" ThisKey="Equipments" OtherKey="Id" Type="Equipment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Equipments" Member="Equipments">
    <Type Name="Equipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Equipment_Car" Member="Cars" ThisKey="Id" OtherKey="Equipments" Type="Car" />
    </Type>
  </Table>
</Database>