<?xml version="1.0" encoding="utf-8"?><Database Name="Cars" Class="linqtosqlclassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Cars.mdf;Integrated Security=True" SettingsObjectName="CarRental.Properties.Settings" SettingsPropertyName="CarsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars_Eqipments" Member="Cars_Eqipments">
    <Type Name="Cars_Eqipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cars_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Equipments_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Equipment_Cars_Eqipment" Member="Equipment" ThisKey="Equipments_id" OtherKey="Id" Type="Equipment" IsForeignKey="true" />
      <Association Name="Car1_Cars_Eqipment" Member="Car" ThisKey="Cars_id" OtherKey="Id" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Equipments" Member="Equipments">
    <Type Name="Equipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Equipment_Cars_Eqipment" Member="Cars_Eqipments" ThisKey="Id" OtherKey="Equipments_id" Type="Cars_Eqipment" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Firts_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Cars_Customer" Member="Cars_Customers" ThisKey="Id" OtherKey="Customer" Type="Cars_Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Cars_Customer" Member="Cars_Customers">
    <Type Name="Cars_Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cars_Eqipment" Member="Car_ID" Storage="_Cars_Eqipment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Cars_Customer" Member="Customer1" ThisKey="Customer" OtherKey="Id" Type="Customer" IsForeignKey="true" />
      <Association Name="Car_Cars_Customer" Member="Car" ThisKey="Car_ID" OtherKey="Id" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Car1_Cars_Eqipment" Member="Cars_Eqipments" ThisKey="Id" OtherKey="Cars_id" Type="Cars_Eqipment" />
      <Association Name="Car_Cars_Customer" Member="Cars_Customers" ThisKey="Id" OtherKey="Car_ID" Type="Cars_Customer" />
    </Type>
  </Table>
</Database>